name: Convert Markdown to EPUB

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown2 ebooklib

      - name: Convert Markdown to EPUB
        run: |
          python md2epub.py

      - name: Creates a release in GitHub and uploads attachments
        run: |
          gh release create ${{ github.ref_name }} ./Palladium_Fantasy_zh_Hans.epub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
